### ISSUE TITLE
cell size

### ISSUE THREAD

**Issue by hellojialee** [TotallyFine/SSD-pytorch#1]
请问您，cell size如何理解，还是不明白。虽然有简略注释。刚学习ssd，请您可以赐教，谢谢！

# cell size是每个feature map中每个cell对应原图的大小
    # 实际产生prior box的时候用的都是相对位置
    cell_size = (8, 16, 32, 64, 100, 300)

**Comment by TotallyFine** [comment]
不好意思之前没有登录github查看信息，假如feature map的宽度为W 长度为H，先忽略其他的维度，那么这个二维平面中的一个方格就是一个cell。假如说原图是300x300，经过几次卷积feature map变为了15x15，那么这里的一个cell就是15x15中的一个格子，对应原图大小就是20x20.

**Comment by TotallyFine** [comment]
对了，请问您是中科大的博士么（´v｀），我看到您的profile上是这样写的。

**Comment by hellojialee** [comment]
谢谢您的回复！第一次看SSD把里面所表述的cell对应原图大小，prior box大小和神经元感受野的概念弄得不太明晰。我是在读生。谢谢回复！
